/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as DeviceLimitRouteImport } from './routes/device-limit'
import { Route as ForcePasswordRouteImport } from './routes/force-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCreateCourseRouteImport } from './routes/admin/create-course'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEmailLogRouteImport } from './routes/admin/email-log'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as ApiCoursesRouteImport } from './routes/api/courses'
import { Route as StudentAccountRouteImport } from './routes/student/account'
import { Route as StudentCourseRouteImport } from './routes/student/course'
import { Route as StudentCoursesRouteImport } from './routes/student/courses'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students.index'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students.$studentId'
import { Route as ApiAdminCoursesRouteImport } from './routes/api/admin/courses'
import { Route as ApiAdminEmailLogRouteImport } from './routes/api/admin/email-log'
import { Route as ApiAdminLessonsRouteImport } from './routes/api/admin/lessons'
import { Route as ApiAdminPaymentsRouteImport } from './routes/api/admin/payments'
import { Route as ApiAdminSectionsRouteImport } from './routes/api/admin/sections'
import { Route as ApiAdminStudentsRouteImport } from './routes/api/admin/students'
import { Route as ApiAuthChangePasswordRouteImport } from './routes/api/auth/change-password'
import { Route as ApiAuthForgotPasswordRouteImport } from './routes/api/auth/forgot-password'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthPendingSessionsRouteImport } from './routes/api/auth/pending-sessions'
import { Route as ApiAuthRefreshRouteImport } from './routes/api/auth/refresh'
import { Route as ApiAuthResetPasswordRouteImport } from './routes/api/auth/reset-password'
import { Route as ApiAuthSessionsRouteImport } from './routes/api/auth/sessions'
import { Route as ApiCoursesIdRouteImport } from './routes/api/courses.$id'
import { Route as ApiPaymentsOrderRouteImport } from './routes/api/payments/order'
import { Route as ApiPaymentsVerifyRouteImport } from './routes/api/payments/verify'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api/payments/webhook'
import { Route as ApiSectionsIdRouteImport } from './routes/api/sections.$id'
import { Route as ApiStudentCoursesRouteImport } from './routes/api/student/courses'
import { Route as ApiStudentProgressRouteImport } from './routes/api/student/progress'
import { Route as ApiAdminCoursesIdRouteImport } from './routes/api/admin/courses.$id'
import { Route as ApiAdminLessonsIdRouteImport } from './routes/api/admin/lessons.$id'
import { Route as ApiAdminSectionsIdRouteImport } from './routes/api/admin/sections.$id'
import { Route as ApiAdminStudentsIdRouteImport } from './routes/api/admin/students.$id'
import { Route as ApiAdminUploadDocumentRouteImport } from './routes/api/admin/upload/document'
import { Route as ApiAdminUploadVideoRouteImport } from './routes/api/admin/upload/video'
import { Route as ApiAuthSessionsIdRouteImport } from './routes/api/auth/sessions.$id'
import { Route as ApiCoursesCourseIdSectionsRouteImport } from './routes/api/courses.$courseId.sections'
import { Route as ApiSectionsSectionIdLessonsRouteImport } from './routes/api/sections.$sectionId.lessons'
import { Route as ApiStudentCoursesIdRouteImport } from './routes/api/student/courses.$id'
import { Route as ApiStudentLessonsIdRouteImport } from './routes/api/student/lessons.$id'
import { Route as ApiStudentProgressLessonIdRouteImport } from './routes/api/student/progress.$lessonId'
import { Route as ApiAdminLessonsIdProgressCheckRouteImport } from './routes/api/admin/lessons.$id.progress-check'
import { Route as ApiAdminLessonsIdPublishRouteImport } from './routes/api/admin/lessons.$id.publish'
import { Route as ApiAdminLessonsIdUnpublishRouteImport } from './routes/api/admin/lessons.$id.unpublish'
import { Route as ApiStudentCoursesIdProgressRouteImport } from './routes/api/student/courses.$id.progress'
import { Route as ApiStudentLessonsIdDocumentRouteImport } from './routes/api/student/lessons.$id.document'
import { Route as ApiStudentLessonsIdProgressRouteImport } from './routes/api/student/lessons.$id.progress'
import { Route as ApiStudentLessonsIdVideoRouteImport } from './routes/api/student/lessons.$id.video'
import { Route as ApiAdminSectionsSectionIdLessonsReorderRouteImport } from './routes/api/admin/sections.$sectionId.lessons.reorder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceLimitRoute = DeviceLimitRouteImport.update({
  id: '/device-limit',
  path: '/device-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcePasswordRoute = ForcePasswordRouteImport.update({
  id: '/force-password',
  path: '/force-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateCourseRoute = AdminCreateCourseRouteImport.update({
  id: '/admin/create-course',
  path: '/admin/create-course',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailLogRoute = AdminEmailLogRouteImport.update({
  id: '/admin/email-log',
  path: '/admin/email-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesRoute = ApiCoursesRouteImport.update({
  id: '/api/courses',
  path: '/api/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAccountRoute = StudentAccountRouteImport.update({
  id: '/student/account',
  path: '/student/account',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCourseRoute = StudentCourseRouteImport.update({
  id: '/student/course',
  path: '/student/course',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/student/courses',
  path: '/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/admin/students/',
  path: '/admin/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/admin/students/$studentId',
  path: '/admin/students/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoursesRoute = ApiAdminCoursesRouteImport.update({
  id: '/api/admin/courses',
  path: '/api/admin/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailLogRoute = ApiAdminEmailLogRouteImport.update({
  id: '/api/admin/email-log',
  path: '/api/admin/email-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLessonsRoute = ApiAdminLessonsRouteImport.update({
  id: '/api/admin/lessons',
  path: '/api/admin/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentsRoute = ApiAdminPaymentsRouteImport.update({
  id: '/api/admin/payments',
  path: '/api/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSectionsRoute = ApiAdminSectionsRouteImport.update({
  id: '/api/admin/sections',
  path: '/api/admin/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStudentsRoute = ApiAdminStudentsRouteImport.update({
  id: '/api/admin/students',
  path: '/api/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthChangePasswordRoute = ApiAuthChangePasswordRouteImport.update({
  id: '/api/auth/change-password',
  path: '/api/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthForgotPasswordRoute = ApiAuthForgotPasswordRouteImport.update({
  id: '/api/auth/forgot-password',
  path: '/api/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPendingSessionsRoute = ApiAuthPendingSessionsRouteImport.update({
  id: '/api/auth/pending-sessions',
  path: '/api/auth/pending-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/api/auth/refresh',
  path: '/api/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthResetPasswordRoute = ApiAuthResetPasswordRouteImport.update({
  id: '/api/auth/reset-password',
  path: '/api/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionsRoute = ApiAuthSessionsRouteImport.update({
  id: '/api/auth/sessions',
  path: '/api/auth/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesIdRoute = ApiCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCoursesRoute,
} as any)
const ApiPaymentsOrderRoute = ApiPaymentsOrderRouteImport.update({
  id: '/api/payments/order',
  path: '/api/payments/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsVerifyRoute = ApiPaymentsVerifyRouteImport.update({
  id: '/api/payments/verify',
  path: '/api/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSectionsIdRoute = ApiSectionsIdRouteImport.update({
  id: '/api/sections/$id',
  path: '/api/sections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentCoursesRoute = ApiStudentCoursesRouteImport.update({
  id: '/api/student/courses',
  path: '/api/student/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentProgressRoute = ApiStudentProgressRouteImport.update({
  id: '/api/student/progress',
  path: '/api/student/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCoursesIdRoute = ApiAdminCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCoursesRoute,
} as any)
const ApiAdminLessonsIdRoute = ApiAdminLessonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminLessonsRoute,
} as any)
const ApiAdminSectionsIdRoute = ApiAdminSectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSectionsRoute,
} as any)
const ApiAdminStudentsIdRoute = ApiAdminStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminStudentsRoute,
} as any)
const ApiAdminUploadDocumentRoute = ApiAdminUploadDocumentRouteImport.update({
  id: '/api/admin/upload/document',
  path: '/api/admin/upload/document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadVideoRoute = ApiAdminUploadVideoRouteImport.update({
  id: '/api/admin/upload/video',
  path: '/api/admin/upload/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionsIdRoute = ApiAuthSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAuthSessionsRoute,
} as any)
const ApiCoursesCourseIdSectionsRoute =
  ApiCoursesCourseIdSectionsRouteImport.update({
    id: '/$courseId/sections',
    path: '/$courseId/sections',
    getParentRoute: () => ApiCoursesRoute,
  } as any)
const ApiSectionsSectionIdLessonsRoute =
  ApiSectionsSectionIdLessonsRouteImport.update({
    id: '/api/sections/$sectionId/lessons',
    path: '/api/sections/$sectionId/lessons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStudentCoursesIdRoute = ApiStudentCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStudentCoursesRoute,
} as any)
const ApiStudentLessonsIdRoute = ApiStudentLessonsIdRouteImport.update({
  id: '/api/student/lessons/$id',
  path: '/api/student/lessons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentProgressLessonIdRoute =
  ApiStudentProgressLessonIdRouteImport.update({
    id: '/$lessonId',
    path: '/$lessonId',
    getParentRoute: () => ApiStudentProgressRoute,
  } as any)
const ApiAdminLessonsIdProgressCheckRoute =
  ApiAdminLessonsIdProgressCheckRouteImport.update({
    id: '/progress-check',
    path: '/progress-check',
    getParentRoute: () => ApiAdminLessonsIdRoute,
  } as any)
const ApiAdminLessonsIdPublishRoute =
  ApiAdminLessonsIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiAdminLessonsIdRoute,
  } as any)
const ApiAdminLessonsIdUnpublishRoute =
  ApiAdminLessonsIdUnpublishRouteImport.update({
    id: '/unpublish',
    path: '/unpublish',
    getParentRoute: () => ApiAdminLessonsIdRoute,
  } as any)
const ApiStudentCoursesIdProgressRoute =
  ApiStudentCoursesIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ApiStudentCoursesIdRoute,
  } as any)
const ApiStudentLessonsIdDocumentRoute =
  ApiStudentLessonsIdDocumentRouteImport.update({
    id: '/document',
    path: '/document',
    getParentRoute: () => ApiStudentLessonsIdRoute,
  } as any)
const ApiStudentLessonsIdProgressRoute =
  ApiStudentLessonsIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ApiStudentLessonsIdRoute,
  } as any)
const ApiStudentLessonsIdVideoRoute =
  ApiStudentLessonsIdVideoRouteImport.update({
    id: '/video',
    path: '/video',
    getParentRoute: () => ApiStudentLessonsIdRoute,
  } as any)
const ApiAdminSectionsSectionIdLessonsReorderRoute =
  ApiAdminSectionsSectionIdLessonsReorderRouteImport.update({
    id: '/$sectionId/lessons/reorder',
    path: '/$sectionId/lessons/reorder',
    getParentRoute: () => ApiAdminSectionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/device-limit': typeof DeviceLimitRoute
  '/force-password': typeof ForcePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/create-course': typeof AdminCreateCourseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-log': typeof AdminEmailLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/courses': typeof ApiCoursesRouteWithChildren
  '/student/account': typeof StudentAccountRoute
  '/student/course': typeof StudentCourseRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/email-log': typeof ApiAdminEmailLogRoute
  '/api/admin/lessons': typeof ApiAdminLessonsRouteWithChildren
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/sections': typeof ApiAdminSectionsRouteWithChildren
  '/api/admin/students': typeof ApiAdminStudentsRouteWithChildren
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pending-sessions': typeof ApiAuthPendingSessionsRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRouteWithChildren
  '/api/courses/$id': typeof ApiCoursesIdRoute
  '/api/payments/order': typeof ApiPaymentsOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/sections/$id': typeof ApiSectionsIdRoute
  '/api/student/courses': typeof ApiStudentCoursesRouteWithChildren
  '/api/student/progress': typeof ApiStudentProgressRouteWithChildren
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/api/admin/courses/$id': typeof ApiAdminCoursesIdRoute
  '/api/admin/lessons/$id': typeof ApiAdminLessonsIdRouteWithChildren
  '/api/admin/sections/$id': typeof ApiAdminSectionsIdRoute
  '/api/admin/students/$id': typeof ApiAdminStudentsIdRoute
  '/api/admin/upload/document': typeof ApiAdminUploadDocumentRoute
  '/api/admin/upload/video': typeof ApiAdminUploadVideoRoute
  '/api/auth/sessions/$id': typeof ApiAuthSessionsIdRoute
  '/api/courses/$courseId/sections': typeof ApiCoursesCourseIdSectionsRoute
  '/api/sections/$sectionId/lessons': typeof ApiSectionsSectionIdLessonsRoute
  '/api/student/courses/$id': typeof ApiStudentCoursesIdRouteWithChildren
  '/api/student/lessons/$id': typeof ApiStudentLessonsIdRouteWithChildren
  '/api/student/progress/$lessonId': typeof ApiStudentProgressLessonIdRoute
  '/api/admin/lessons/$id/progress-check': typeof ApiAdminLessonsIdProgressCheckRoute
  '/api/admin/lessons/$id/publish': typeof ApiAdminLessonsIdPublishRoute
  '/api/admin/lessons/$id/unpublish': typeof ApiAdminLessonsIdUnpublishRoute
  '/api/student/courses/$id/progress': typeof ApiStudentCoursesIdProgressRoute
  '/api/student/lessons/$id/document': typeof ApiStudentLessonsIdDocumentRoute
  '/api/student/lessons/$id/progress': typeof ApiStudentLessonsIdProgressRoute
  '/api/student/lessons/$id/video': typeof ApiStudentLessonsIdVideoRoute
  '/api/admin/sections/$sectionId/lessons/reorder': typeof ApiAdminSectionsSectionIdLessonsReorderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/device-limit': typeof DeviceLimitRoute
  '/force-password': typeof ForcePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/create-course': typeof AdminCreateCourseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-log': typeof AdminEmailLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/courses': typeof ApiCoursesRouteWithChildren
  '/student/account': typeof StudentAccountRoute
  '/student/course': typeof StudentCourseRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/email-log': typeof ApiAdminEmailLogRoute
  '/api/admin/lessons': typeof ApiAdminLessonsRouteWithChildren
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/sections': typeof ApiAdminSectionsRouteWithChildren
  '/api/admin/students': typeof ApiAdminStudentsRouteWithChildren
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pending-sessions': typeof ApiAuthPendingSessionsRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRouteWithChildren
  '/api/courses/$id': typeof ApiCoursesIdRoute
  '/api/payments/order': typeof ApiPaymentsOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/sections/$id': typeof ApiSectionsIdRoute
  '/api/student/courses': typeof ApiStudentCoursesRouteWithChildren
  '/api/student/progress': typeof ApiStudentProgressRouteWithChildren
  '/admin/students': typeof AdminStudentsIndexRoute
  '/api/admin/courses/$id': typeof ApiAdminCoursesIdRoute
  '/api/admin/lessons/$id': typeof ApiAdminLessonsIdRouteWithChildren
  '/api/admin/sections/$id': typeof ApiAdminSectionsIdRoute
  '/api/admin/students/$id': typeof ApiAdminStudentsIdRoute
  '/api/admin/upload/document': typeof ApiAdminUploadDocumentRoute
  '/api/admin/upload/video': typeof ApiAdminUploadVideoRoute
  '/api/auth/sessions/$id': typeof ApiAuthSessionsIdRoute
  '/api/courses/$courseId/sections': typeof ApiCoursesCourseIdSectionsRoute
  '/api/sections/$sectionId/lessons': typeof ApiSectionsSectionIdLessonsRoute
  '/api/student/courses/$id': typeof ApiStudentCoursesIdRouteWithChildren
  '/api/student/lessons/$id': typeof ApiStudentLessonsIdRouteWithChildren
  '/api/student/progress/$lessonId': typeof ApiStudentProgressLessonIdRoute
  '/api/admin/lessons/$id/progress-check': typeof ApiAdminLessonsIdProgressCheckRoute
  '/api/admin/lessons/$id/publish': typeof ApiAdminLessonsIdPublishRoute
  '/api/admin/lessons/$id/unpublish': typeof ApiAdminLessonsIdUnpublishRoute
  '/api/student/courses/$id/progress': typeof ApiStudentCoursesIdProgressRoute
  '/api/student/lessons/$id/document': typeof ApiStudentLessonsIdDocumentRoute
  '/api/student/lessons/$id/progress': typeof ApiStudentLessonsIdProgressRoute
  '/api/student/lessons/$id/video': typeof ApiStudentLessonsIdVideoRoute
  '/api/admin/sections/$sectionId/lessons/reorder': typeof ApiAdminSectionsSectionIdLessonsReorderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/copyright': typeof CopyrightRoute
  '/device-limit': typeof DeviceLimitRoute
  '/force-password': typeof ForcePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media': typeof SocialMediaRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/create-course': typeof AdminCreateCourseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/email-log': typeof AdminEmailLogRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/api/courses': typeof ApiCoursesRouteWithChildren
  '/student/account': typeof StudentAccountRoute
  '/student/course': typeof StudentCourseRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/api/admin/courses': typeof ApiAdminCoursesRouteWithChildren
  '/api/admin/email-log': typeof ApiAdminEmailLogRoute
  '/api/admin/lessons': typeof ApiAdminLessonsRouteWithChildren
  '/api/admin/payments': typeof ApiAdminPaymentsRoute
  '/api/admin/sections': typeof ApiAdminSectionsRouteWithChildren
  '/api/admin/students': typeof ApiAdminStudentsRouteWithChildren
  '/api/auth/change-password': typeof ApiAuthChangePasswordRoute
  '/api/auth/forgot-password': typeof ApiAuthForgotPasswordRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/pending-sessions': typeof ApiAuthPendingSessionsRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
  '/api/auth/reset-password': typeof ApiAuthResetPasswordRoute
  '/api/auth/sessions': typeof ApiAuthSessionsRouteWithChildren
  '/api/courses/$id': typeof ApiCoursesIdRoute
  '/api/payments/order': typeof ApiPaymentsOrderRoute
  '/api/payments/verify': typeof ApiPaymentsVerifyRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/api/sections/$id': typeof ApiSectionsIdRoute
  '/api/student/courses': typeof ApiStudentCoursesRouteWithChildren
  '/api/student/progress': typeof ApiStudentProgressRouteWithChildren
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/api/admin/courses/$id': typeof ApiAdminCoursesIdRoute
  '/api/admin/lessons/$id': typeof ApiAdminLessonsIdRouteWithChildren
  '/api/admin/sections/$id': typeof ApiAdminSectionsIdRoute
  '/api/admin/students/$id': typeof ApiAdminStudentsIdRoute
  '/api/admin/upload/document': typeof ApiAdminUploadDocumentRoute
  '/api/admin/upload/video': typeof ApiAdminUploadVideoRoute
  '/api/auth/sessions/$id': typeof ApiAuthSessionsIdRoute
  '/api/courses/$courseId/sections': typeof ApiCoursesCourseIdSectionsRoute
  '/api/sections/$sectionId/lessons': typeof ApiSectionsSectionIdLessonsRoute
  '/api/student/courses/$id': typeof ApiStudentCoursesIdRouteWithChildren
  '/api/student/lessons/$id': typeof ApiStudentLessonsIdRouteWithChildren
  '/api/student/progress/$lessonId': typeof ApiStudentProgressLessonIdRoute
  '/api/admin/lessons/$id/progress-check': typeof ApiAdminLessonsIdProgressCheckRoute
  '/api/admin/lessons/$id/publish': typeof ApiAdminLessonsIdPublishRoute
  '/api/admin/lessons/$id/unpublish': typeof ApiAdminLessonsIdUnpublishRoute
  '/api/student/courses/$id/progress': typeof ApiStudentCoursesIdProgressRoute
  '/api/student/lessons/$id/document': typeof ApiStudentLessonsIdDocumentRoute
  '/api/student/lessons/$id/progress': typeof ApiStudentLessonsIdProgressRoute
  '/api/student/lessons/$id/video': typeof ApiStudentLessonsIdVideoRoute
  '/api/admin/sections/$sectionId/lessons/reorder': typeof ApiAdminSectionsSectionIdLessonsReorderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/copyright'
    | '/device-limit'
    | '/force-password'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/social-media'
    | '/subscription'
    | '/terms'
    | '/admin/content'
    | '/admin/create-course'
    | '/admin/dashboard'
    | '/admin/email-log'
    | '/admin/payments'
    | '/api/courses'
    | '/student/account'
    | '/student/course'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin/students/$studentId'
    | '/api/admin/courses'
    | '/api/admin/email-log'
    | '/api/admin/lessons'
    | '/api/admin/payments'
    | '/api/admin/sections'
    | '/api/admin/students'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pending-sessions'
    | '/api/auth/refresh'
    | '/api/auth/reset-password'
    | '/api/auth/sessions'
    | '/api/courses/$id'
    | '/api/payments/order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/api/sections/$id'
    | '/api/student/courses'
    | '/api/student/progress'
    | '/admin/students/'
    | '/api/admin/courses/$id'
    | '/api/admin/lessons/$id'
    | '/api/admin/sections/$id'
    | '/api/admin/students/$id'
    | '/api/admin/upload/document'
    | '/api/admin/upload/video'
    | '/api/auth/sessions/$id'
    | '/api/courses/$courseId/sections'
    | '/api/sections/$sectionId/lessons'
    | '/api/student/courses/$id'
    | '/api/student/lessons/$id'
    | '/api/student/progress/$lessonId'
    | '/api/admin/lessons/$id/progress-check'
    | '/api/admin/lessons/$id/publish'
    | '/api/admin/lessons/$id/unpublish'
    | '/api/student/courses/$id/progress'
    | '/api/student/lessons/$id/document'
    | '/api/student/lessons/$id/progress'
    | '/api/student/lessons/$id/video'
    | '/api/admin/sections/$sectionId/lessons/reorder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/copyright'
    | '/device-limit'
    | '/force-password'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/social-media'
    | '/subscription'
    | '/terms'
    | '/admin/content'
    | '/admin/create-course'
    | '/admin/dashboard'
    | '/admin/email-log'
    | '/admin/payments'
    | '/api/courses'
    | '/student/account'
    | '/student/course'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin/students/$studentId'
    | '/api/admin/courses'
    | '/api/admin/email-log'
    | '/api/admin/lessons'
    | '/api/admin/payments'
    | '/api/admin/sections'
    | '/api/admin/students'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pending-sessions'
    | '/api/auth/refresh'
    | '/api/auth/reset-password'
    | '/api/auth/sessions'
    | '/api/courses/$id'
    | '/api/payments/order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/api/sections/$id'
    | '/api/student/courses'
    | '/api/student/progress'
    | '/admin/students'
    | '/api/admin/courses/$id'
    | '/api/admin/lessons/$id'
    | '/api/admin/sections/$id'
    | '/api/admin/students/$id'
    | '/api/admin/upload/document'
    | '/api/admin/upload/video'
    | '/api/auth/sessions/$id'
    | '/api/courses/$courseId/sections'
    | '/api/sections/$sectionId/lessons'
    | '/api/student/courses/$id'
    | '/api/student/lessons/$id'
    | '/api/student/progress/$lessonId'
    | '/api/admin/lessons/$id/progress-check'
    | '/api/admin/lessons/$id/publish'
    | '/api/admin/lessons/$id/unpublish'
    | '/api/student/courses/$id/progress'
    | '/api/student/lessons/$id/document'
    | '/api/student/lessons/$id/progress'
    | '/api/student/lessons/$id/video'
    | '/api/admin/sections/$sectionId/lessons/reorder'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/copyright'
    | '/device-limit'
    | '/force-password'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/social-media'
    | '/subscription'
    | '/terms'
    | '/admin/content'
    | '/admin/create-course'
    | '/admin/dashboard'
    | '/admin/email-log'
    | '/admin/payments'
    | '/api/courses'
    | '/student/account'
    | '/student/course'
    | '/student/courses'
    | '/student/dashboard'
    | '/admin/students/$studentId'
    | '/api/admin/courses'
    | '/api/admin/email-log'
    | '/api/admin/lessons'
    | '/api/admin/payments'
    | '/api/admin/sections'
    | '/api/admin/students'
    | '/api/auth/change-password'
    | '/api/auth/forgot-password'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/pending-sessions'
    | '/api/auth/refresh'
    | '/api/auth/reset-password'
    | '/api/auth/sessions'
    | '/api/courses/$id'
    | '/api/payments/order'
    | '/api/payments/verify'
    | '/api/payments/webhook'
    | '/api/sections/$id'
    | '/api/student/courses'
    | '/api/student/progress'
    | '/admin/students/'
    | '/api/admin/courses/$id'
    | '/api/admin/lessons/$id'
    | '/api/admin/sections/$id'
    | '/api/admin/students/$id'
    | '/api/admin/upload/document'
    | '/api/admin/upload/video'
    | '/api/auth/sessions/$id'
    | '/api/courses/$courseId/sections'
    | '/api/sections/$sectionId/lessons'
    | '/api/student/courses/$id'
    | '/api/student/lessons/$id'
    | '/api/student/progress/$lessonId'
    | '/api/admin/lessons/$id/progress-check'
    | '/api/admin/lessons/$id/publish'
    | '/api/admin/lessons/$id/unpublish'
    | '/api/student/courses/$id/progress'
    | '/api/student/lessons/$id/document'
    | '/api/student/lessons/$id/progress'
    | '/api/student/lessons/$id/video'
    | '/api/admin/sections/$sectionId/lessons/reorder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  CopyrightRoute: typeof CopyrightRoute
  DeviceLimitRoute: typeof DeviceLimitRoute
  ForcePasswordRoute: typeof ForcePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialMediaRoute: typeof SocialMediaRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCreateCourseRoute: typeof AdminCreateCourseRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailLogRoute: typeof AdminEmailLogRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  ApiCoursesRoute: typeof ApiCoursesRouteWithChildren
  StudentAccountRoute: typeof StudentAccountRoute
  StudentCourseRoute: typeof StudentCourseRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
  ApiAdminCoursesRoute: typeof ApiAdminCoursesRouteWithChildren
  ApiAdminEmailLogRoute: typeof ApiAdminEmailLogRoute
  ApiAdminLessonsRoute: typeof ApiAdminLessonsRouteWithChildren
  ApiAdminPaymentsRoute: typeof ApiAdminPaymentsRoute
  ApiAdminSectionsRoute: typeof ApiAdminSectionsRouteWithChildren
  ApiAdminStudentsRoute: typeof ApiAdminStudentsRouteWithChildren
  ApiAuthChangePasswordRoute: typeof ApiAuthChangePasswordRoute
  ApiAuthForgotPasswordRoute: typeof ApiAuthForgotPasswordRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthPendingSessionsRoute: typeof ApiAuthPendingSessionsRoute
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
  ApiAuthResetPasswordRoute: typeof ApiAuthResetPasswordRoute
  ApiAuthSessionsRoute: typeof ApiAuthSessionsRouteWithChildren
  ApiPaymentsOrderRoute: typeof ApiPaymentsOrderRoute
  ApiPaymentsVerifyRoute: typeof ApiPaymentsVerifyRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  ApiSectionsIdRoute: typeof ApiSectionsIdRoute
  ApiStudentCoursesRoute: typeof ApiStudentCoursesRouteWithChildren
  ApiStudentProgressRoute: typeof ApiStudentProgressRouteWithChildren
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  ApiAdminUploadDocumentRoute: typeof ApiAdminUploadDocumentRoute
  ApiAdminUploadVideoRoute: typeof ApiAdminUploadVideoRoute
  ApiSectionsSectionIdLessonsRoute: typeof ApiSectionsSectionIdLessonsRoute
  ApiStudentLessonsIdRoute: typeof ApiStudentLessonsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device-limit': {
      id: '/device-limit'
      path: '/device-limit'
      fullPath: '/device-limit'
      preLoaderRoute: typeof DeviceLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-password': {
      id: '/force-password'
      path: '/force-password'
      fullPath: '/force-password'
      preLoaderRoute: typeof ForcePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-course': {
      id: '/admin/create-course'
      path: '/admin/create-course'
      fullPath: '/admin/create-course'
      preLoaderRoute: typeof AdminCreateCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/email-log': {
      id: '/admin/email-log'
      path: '/admin/email-log'
      fullPath: '/admin/email-log'
      preLoaderRoute: typeof AdminEmailLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses': {
      id: '/api/courses'
      path: '/api/courses'
      fullPath: '/api/courses'
      preLoaderRoute: typeof ApiCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/account': {
      id: '/student/account'
      path: '/student/account'
      fullPath: '/student/account'
      preLoaderRoute: typeof StudentAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/course': {
      id: '/student/course'
      path: '/student/course'
      fullPath: '/student/course'
      preLoaderRoute: typeof StudentCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/student/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/admin/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/courses': {
      id: '/api/admin/courses'
      path: '/api/admin/courses'
      fullPath: '/api/admin/courses'
      preLoaderRoute: typeof ApiAdminCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/email-log': {
      id: '/api/admin/email-log'
      path: '/api/admin/email-log'
      fullPath: '/api/admin/email-log'
      preLoaderRoute: typeof ApiAdminEmailLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/lessons': {
      id: '/api/admin/lessons'
      path: '/api/admin/lessons'
      fullPath: '/api/admin/lessons'
      preLoaderRoute: typeof ApiAdminLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payments': {
      id: '/api/admin/payments'
      path: '/api/admin/payments'
      fullPath: '/api/admin/payments'
      preLoaderRoute: typeof ApiAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sections': {
      id: '/api/admin/sections'
      path: '/api/admin/sections'
      fullPath: '/api/admin/sections'
      preLoaderRoute: typeof ApiAdminSectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/students': {
      id: '/api/admin/students'
      path: '/api/admin/students'
      fullPath: '/api/admin/students'
      preLoaderRoute: typeof ApiAdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/change-password': {
      id: '/api/auth/change-password'
      path: '/api/auth/change-password'
      fullPath: '/api/auth/change-password'
      preLoaderRoute: typeof ApiAuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/forgot-password': {
      id: '/api/auth/forgot-password'
      path: '/api/auth/forgot-password'
      fullPath: '/api/auth/forgot-password'
      preLoaderRoute: typeof ApiAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/pending-sessions': {
      id: '/api/auth/pending-sessions'
      path: '/api/auth/pending-sessions'
      fullPath: '/api/auth/pending-sessions'
      preLoaderRoute: typeof ApiAuthPendingSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/api/auth/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/reset-password': {
      id: '/api/auth/reset-password'
      path: '/api/auth/reset-password'
      fullPath: '/api/auth/reset-password'
      preLoaderRoute: typeof ApiAuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sessions': {
      id: '/api/auth/sessions'
      path: '/api/auth/sessions'
      fullPath: '/api/auth/sessions'
      preLoaderRoute: typeof ApiAuthSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses/$id': {
      id: '/api/courses/$id'
      path: '/$id'
      fullPath: '/api/courses/$id'
      preLoaderRoute: typeof ApiCoursesIdRouteImport
      parentRoute: typeof ApiCoursesRoute
    }
    '/api/payments/order': {
      id: '/api/payments/order'
      path: '/api/payments/order'
      fullPath: '/api/payments/order'
      preLoaderRoute: typeof ApiPaymentsOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/verify': {
      id: '/api/payments/verify'
      path: '/api/payments/verify'
      fullPath: '/api/payments/verify'
      preLoaderRoute: typeof ApiPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sections/$id': {
      id: '/api/sections/$id'
      path: '/api/sections/$id'
      fullPath: '/api/sections/$id'
      preLoaderRoute: typeof ApiSectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student/courses': {
      id: '/api/student/courses'
      path: '/api/student/courses'
      fullPath: '/api/student/courses'
      preLoaderRoute: typeof ApiStudentCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student/progress': {
      id: '/api/student/progress'
      path: '/api/student/progress'
      fullPath: '/api/student/progress'
      preLoaderRoute: typeof ApiStudentProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/courses/$id': {
      id: '/api/admin/courses/$id'
      path: '/$id'
      fullPath: '/api/admin/courses/$id'
      preLoaderRoute: typeof ApiAdminCoursesIdRouteImport
      parentRoute: typeof ApiAdminCoursesRoute
    }
    '/api/admin/lessons/$id': {
      id: '/api/admin/lessons/$id'
      path: '/$id'
      fullPath: '/api/admin/lessons/$id'
      preLoaderRoute: typeof ApiAdminLessonsIdRouteImport
      parentRoute: typeof ApiAdminLessonsRoute
    }
    '/api/admin/sections/$id': {
      id: '/api/admin/sections/$id'
      path: '/$id'
      fullPath: '/api/admin/sections/$id'
      preLoaderRoute: typeof ApiAdminSectionsIdRouteImport
      parentRoute: typeof ApiAdminSectionsRoute
    }
    '/api/admin/students/$id': {
      id: '/api/admin/students/$id'
      path: '/$id'
      fullPath: '/api/admin/students/$id'
      preLoaderRoute: typeof ApiAdminStudentsIdRouteImport
      parentRoute: typeof ApiAdminStudentsRoute
    }
    '/api/admin/upload/document': {
      id: '/api/admin/upload/document'
      path: '/api/admin/upload/document'
      fullPath: '/api/admin/upload/document'
      preLoaderRoute: typeof ApiAdminUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload/video': {
      id: '/api/admin/upload/video'
      path: '/api/admin/upload/video'
      fullPath: '/api/admin/upload/video'
      preLoaderRoute: typeof ApiAdminUploadVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sessions/$id': {
      id: '/api/auth/sessions/$id'
      path: '/$id'
      fullPath: '/api/auth/sessions/$id'
      preLoaderRoute: typeof ApiAuthSessionsIdRouteImport
      parentRoute: typeof ApiAuthSessionsRoute
    }
    '/api/courses/$courseId/sections': {
      id: '/api/courses/$courseId/sections'
      path: '/$courseId/sections'
      fullPath: '/api/courses/$courseId/sections'
      preLoaderRoute: typeof ApiCoursesCourseIdSectionsRouteImport
      parentRoute: typeof ApiCoursesRoute
    }
    '/api/sections/$sectionId/lessons': {
      id: '/api/sections/$sectionId/lessons'
      path: '/api/sections/$sectionId/lessons'
      fullPath: '/api/sections/$sectionId/lessons'
      preLoaderRoute: typeof ApiSectionsSectionIdLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student/courses/$id': {
      id: '/api/student/courses/$id'
      path: '/$id'
      fullPath: '/api/student/courses/$id'
      preLoaderRoute: typeof ApiStudentCoursesIdRouteImport
      parentRoute: typeof ApiStudentCoursesRoute
    }
    '/api/student/lessons/$id': {
      id: '/api/student/lessons/$id'
      path: '/api/student/lessons/$id'
      fullPath: '/api/student/lessons/$id'
      preLoaderRoute: typeof ApiStudentLessonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/student/progress/$lessonId': {
      id: '/api/student/progress/$lessonId'
      path: '/$lessonId'
      fullPath: '/api/student/progress/$lessonId'
      preLoaderRoute: typeof ApiStudentProgressLessonIdRouteImport
      parentRoute: typeof ApiStudentProgressRoute
    }
    '/api/admin/lessons/$id/progress-check': {
      id: '/api/admin/lessons/$id/progress-check'
      path: '/progress-check'
      fullPath: '/api/admin/lessons/$id/progress-check'
      preLoaderRoute: typeof ApiAdminLessonsIdProgressCheckRouteImport
      parentRoute: typeof ApiAdminLessonsIdRoute
    }
    '/api/admin/lessons/$id/publish': {
      id: '/api/admin/lessons/$id/publish'
      path: '/publish'
      fullPath: '/api/admin/lessons/$id/publish'
      preLoaderRoute: typeof ApiAdminLessonsIdPublishRouteImport
      parentRoute: typeof ApiAdminLessonsIdRoute
    }
    '/api/admin/lessons/$id/unpublish': {
      id: '/api/admin/lessons/$id/unpublish'
      path: '/unpublish'
      fullPath: '/api/admin/lessons/$id/unpublish'
      preLoaderRoute: typeof ApiAdminLessonsIdUnpublishRouteImport
      parentRoute: typeof ApiAdminLessonsIdRoute
    }
    '/api/student/courses/$id/progress': {
      id: '/api/student/courses/$id/progress'
      path: '/progress'
      fullPath: '/api/student/courses/$id/progress'
      preLoaderRoute: typeof ApiStudentCoursesIdProgressRouteImport
      parentRoute: typeof ApiStudentCoursesIdRoute
    }
    '/api/student/lessons/$id/document': {
      id: '/api/student/lessons/$id/document'
      path: '/document'
      fullPath: '/api/student/lessons/$id/document'
      preLoaderRoute: typeof ApiStudentLessonsIdDocumentRouteImport
      parentRoute: typeof ApiStudentLessonsIdRoute
    }
    '/api/student/lessons/$id/progress': {
      id: '/api/student/lessons/$id/progress'
      path: '/progress'
      fullPath: '/api/student/lessons/$id/progress'
      preLoaderRoute: typeof ApiStudentLessonsIdProgressRouteImport
      parentRoute: typeof ApiStudentLessonsIdRoute
    }
    '/api/student/lessons/$id/video': {
      id: '/api/student/lessons/$id/video'
      path: '/video'
      fullPath: '/api/student/lessons/$id/video'
      preLoaderRoute: typeof ApiStudentLessonsIdVideoRouteImport
      parentRoute: typeof ApiStudentLessonsIdRoute
    }
    '/api/admin/sections/$sectionId/lessons/reorder': {
      id: '/api/admin/sections/$sectionId/lessons/reorder'
      path: '/$sectionId/lessons/reorder'
      fullPath: '/api/admin/sections/$sectionId/lessons/reorder'
      preLoaderRoute: typeof ApiAdminSectionsSectionIdLessonsReorderRouteImport
      parentRoute: typeof ApiAdminSectionsRoute
    }
  }
}

interface ApiCoursesRouteChildren {
  ApiCoursesIdRoute: typeof ApiCoursesIdRoute
  ApiCoursesCourseIdSectionsRoute: typeof ApiCoursesCourseIdSectionsRoute
}

const ApiCoursesRouteChildren: ApiCoursesRouteChildren = {
  ApiCoursesIdRoute: ApiCoursesIdRoute,
  ApiCoursesCourseIdSectionsRoute: ApiCoursesCourseIdSectionsRoute,
}

const ApiCoursesRouteWithChildren = ApiCoursesRoute._addFileChildren(
  ApiCoursesRouteChildren,
)

interface ApiAdminCoursesRouteChildren {
  ApiAdminCoursesIdRoute: typeof ApiAdminCoursesIdRoute
}

const ApiAdminCoursesRouteChildren: ApiAdminCoursesRouteChildren = {
  ApiAdminCoursesIdRoute: ApiAdminCoursesIdRoute,
}

const ApiAdminCoursesRouteWithChildren = ApiAdminCoursesRoute._addFileChildren(
  ApiAdminCoursesRouteChildren,
)

interface ApiAdminLessonsIdRouteChildren {
  ApiAdminLessonsIdProgressCheckRoute: typeof ApiAdminLessonsIdProgressCheckRoute
  ApiAdminLessonsIdPublishRoute: typeof ApiAdminLessonsIdPublishRoute
  ApiAdminLessonsIdUnpublishRoute: typeof ApiAdminLessonsIdUnpublishRoute
}

const ApiAdminLessonsIdRouteChildren: ApiAdminLessonsIdRouteChildren = {
  ApiAdminLessonsIdProgressCheckRoute: ApiAdminLessonsIdProgressCheckRoute,
  ApiAdminLessonsIdPublishRoute: ApiAdminLessonsIdPublishRoute,
  ApiAdminLessonsIdUnpublishRoute: ApiAdminLessonsIdUnpublishRoute,
}

const ApiAdminLessonsIdRouteWithChildren =
  ApiAdminLessonsIdRoute._addFileChildren(ApiAdminLessonsIdRouteChildren)

interface ApiAdminLessonsRouteChildren {
  ApiAdminLessonsIdRoute: typeof ApiAdminLessonsIdRouteWithChildren
}

const ApiAdminLessonsRouteChildren: ApiAdminLessonsRouteChildren = {
  ApiAdminLessonsIdRoute: ApiAdminLessonsIdRouteWithChildren,
}

const ApiAdminLessonsRouteWithChildren = ApiAdminLessonsRoute._addFileChildren(
  ApiAdminLessonsRouteChildren,
)

interface ApiAdminSectionsRouteChildren {
  ApiAdminSectionsIdRoute: typeof ApiAdminSectionsIdRoute
  ApiAdminSectionsSectionIdLessonsReorderRoute: typeof ApiAdminSectionsSectionIdLessonsReorderRoute
}

const ApiAdminSectionsRouteChildren: ApiAdminSectionsRouteChildren = {
  ApiAdminSectionsIdRoute: ApiAdminSectionsIdRoute,
  ApiAdminSectionsSectionIdLessonsReorderRoute:
    ApiAdminSectionsSectionIdLessonsReorderRoute,
}

const ApiAdminSectionsRouteWithChildren =
  ApiAdminSectionsRoute._addFileChildren(ApiAdminSectionsRouteChildren)

interface ApiAdminStudentsRouteChildren {
  ApiAdminStudentsIdRoute: typeof ApiAdminStudentsIdRoute
}

const ApiAdminStudentsRouteChildren: ApiAdminStudentsRouteChildren = {
  ApiAdminStudentsIdRoute: ApiAdminStudentsIdRoute,
}

const ApiAdminStudentsRouteWithChildren =
  ApiAdminStudentsRoute._addFileChildren(ApiAdminStudentsRouteChildren)

interface ApiAuthSessionsRouteChildren {
  ApiAuthSessionsIdRoute: typeof ApiAuthSessionsIdRoute
}

const ApiAuthSessionsRouteChildren: ApiAuthSessionsRouteChildren = {
  ApiAuthSessionsIdRoute: ApiAuthSessionsIdRoute,
}

const ApiAuthSessionsRouteWithChildren = ApiAuthSessionsRoute._addFileChildren(
  ApiAuthSessionsRouteChildren,
)

interface ApiStudentCoursesIdRouteChildren {
  ApiStudentCoursesIdProgressRoute: typeof ApiStudentCoursesIdProgressRoute
}

const ApiStudentCoursesIdRouteChildren: ApiStudentCoursesIdRouteChildren = {
  ApiStudentCoursesIdProgressRoute: ApiStudentCoursesIdProgressRoute,
}

const ApiStudentCoursesIdRouteWithChildren =
  ApiStudentCoursesIdRoute._addFileChildren(ApiStudentCoursesIdRouteChildren)

interface ApiStudentCoursesRouteChildren {
  ApiStudentCoursesIdRoute: typeof ApiStudentCoursesIdRouteWithChildren
}

const ApiStudentCoursesRouteChildren: ApiStudentCoursesRouteChildren = {
  ApiStudentCoursesIdRoute: ApiStudentCoursesIdRouteWithChildren,
}

const ApiStudentCoursesRouteWithChildren =
  ApiStudentCoursesRoute._addFileChildren(ApiStudentCoursesRouteChildren)

interface ApiStudentProgressRouteChildren {
  ApiStudentProgressLessonIdRoute: typeof ApiStudentProgressLessonIdRoute
}

const ApiStudentProgressRouteChildren: ApiStudentProgressRouteChildren = {
  ApiStudentProgressLessonIdRoute: ApiStudentProgressLessonIdRoute,
}

const ApiStudentProgressRouteWithChildren =
  ApiStudentProgressRoute._addFileChildren(ApiStudentProgressRouteChildren)

interface ApiStudentLessonsIdRouteChildren {
  ApiStudentLessonsIdDocumentRoute: typeof ApiStudentLessonsIdDocumentRoute
  ApiStudentLessonsIdProgressRoute: typeof ApiStudentLessonsIdProgressRoute
  ApiStudentLessonsIdVideoRoute: typeof ApiStudentLessonsIdVideoRoute
}

const ApiStudentLessonsIdRouteChildren: ApiStudentLessonsIdRouteChildren = {
  ApiStudentLessonsIdDocumentRoute: ApiStudentLessonsIdDocumentRoute,
  ApiStudentLessonsIdProgressRoute: ApiStudentLessonsIdProgressRoute,
  ApiStudentLessonsIdVideoRoute: ApiStudentLessonsIdVideoRoute,
}

const ApiStudentLessonsIdRouteWithChildren =
  ApiStudentLessonsIdRoute._addFileChildren(ApiStudentLessonsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  CopyrightRoute: CopyrightRoute,
  DeviceLimitRoute: DeviceLimitRoute,
  ForcePasswordRoute: ForcePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialMediaRoute: SocialMediaRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCreateCourseRoute: AdminCreateCourseRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailLogRoute: AdminEmailLogRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  ApiCoursesRoute: ApiCoursesRouteWithChildren,
  StudentAccountRoute: StudentAccountRoute,
  StudentCourseRoute: StudentCourseRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
  ApiAdminCoursesRoute: ApiAdminCoursesRouteWithChildren,
  ApiAdminEmailLogRoute: ApiAdminEmailLogRoute,
  ApiAdminLessonsRoute: ApiAdminLessonsRouteWithChildren,
  ApiAdminPaymentsRoute: ApiAdminPaymentsRoute,
  ApiAdminSectionsRoute: ApiAdminSectionsRouteWithChildren,
  ApiAdminStudentsRoute: ApiAdminStudentsRouteWithChildren,
  ApiAuthChangePasswordRoute: ApiAuthChangePasswordRoute,
  ApiAuthForgotPasswordRoute: ApiAuthForgotPasswordRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthPendingSessionsRoute: ApiAuthPendingSessionsRoute,
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
  ApiAuthResetPasswordRoute: ApiAuthResetPasswordRoute,
  ApiAuthSessionsRoute: ApiAuthSessionsRouteWithChildren,
  ApiPaymentsOrderRoute: ApiPaymentsOrderRoute,
  ApiPaymentsVerifyRoute: ApiPaymentsVerifyRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  ApiSectionsIdRoute: ApiSectionsIdRoute,
  ApiStudentCoursesRoute: ApiStudentCoursesRouteWithChildren,
  ApiStudentProgressRoute: ApiStudentProgressRouteWithChildren,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  ApiAdminUploadDocumentRoute: ApiAdminUploadDocumentRoute,
  ApiAdminUploadVideoRoute: ApiAdminUploadVideoRoute,
  ApiSectionsSectionIdLessonsRoute: ApiSectionsSectionIdLessonsRoute,
  ApiStudentLessonsIdRoute: ApiStudentLessonsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
